name: E2E Testing
on:
  - pull_request
  - workflow_dispatch

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Build SASS
        run: npm run build
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
      - name: Generate E2E Test Badge
        run: echo -n "![E2E Test Status](https://img.shields.io/badge/E2E%20Test-Passed-brightgreen)" > README.md
        if: success()
